name:                parser-hs
version:             0.1.0.0
github:              "githubuser/parser-hs"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/parser-hs#readme>

dependencies:
- base >= 4.7 && < 5
- haskell-src-exts
- directory
- filepath
- haskell-src-exts
- regex-compat
- text
- pretty-simple
- lens
- generic-lens
- unordered-containers
- hashable
- aeson
- aeson-pretty
- ghc
- bytestring

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  parser-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parser-hs
    default-extensions:
    - StandaloneDeriving
    - FlexibleInstances
    - DeriveAnyClass
    - DuplicateRecordFields
    - DeriveGeneric
    - OverloadedLabels
    - AllowAmbiguousTypes
    - DataKinds
    - DeriveGeneric
    - DuplicateRecordFields
    - FlexibleContexts
    - NoMonomorphismRestriction
    - TypeApplications
    - ScopedTypeVariables
    - RecordWildCards
    - BangPatterns
    - OverloadedStrings
